### ISSUE TITLE
Support for Thymeleaf 3.0

### ISSUE THREAD

**Issue by ebussieres** [Antibrumm/thymeleaf-extras-cache-dialect#1]
Thymeleaf 3.0 will change the API for dialects. It'll need to be updated.

**Comment by Antibrumm** [comment]
Thanks. I will take a look at it once i have some spare time.
Reference: https://github.com/thymeleaf/thymeleaf/issues/401

**Comment by Antibrumm** [comment]
A first version running against 3.0.0.BETA01 is now available as SNAPSHOT
https://github.com/Antibrumm/thymeleaf-extras-cache-dialect/commit/eaf2c5b0b73bb85941c420018e3b5ed4410713e8
